deployment_frequency:
    resource:
        methods: [POST]
        path: ../src/Domains/DeploymentFrequency/Infrastructure/Http/Controller/
        namespace: App\Domains\DeploymentFrequency\Infrastructure\Http\Controller
    type: attribute

lead_time_for_changes:
    resource:
        methods: [POST]
        path: ../src/Domains/LeadTimeForChanges/Application/Controller/
        namespace: App\LeadTimeForChanges\Api
    type: attribute



