parameters:

services:
    App\Domains\DeploymentFrequency\Domain\DeploymentRepositoryInterface:
        class: App\Domains\DeploymentFrequency\Infrastructure\Persistence\InMemoryDeploymentRepository
